<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Acm.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeJam" Version="4.1.0" />
    <PackageReference Include="EPPlus" Version="8.4.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DB\DB.csproj" />
    <ProjectReference Include="..\OperationsParser\OperationsParser.csproj" />
  </ItemGroup>

</Project>
